#!/bin/bash

git filter-branch --force --commit-filter 'export GIT_AUTHOR_NAME="Andrew Young"; export GIT_AUTHOR_EMAIL=andrew@vaelen.org; export GIT_COMMITTER_NAME="Andrew Young"; export GIT_COMMITTER_EMAIL=andrew@vaelen.org; git commit-tree "$@"'
