#!/bin/bash

for f in *; do
    if [[ -d "$f" ]]; then
        pushd $f >/dev/null
        if [[ -d ".git" ]]; then
            status=$(git status -s -uno)
            if [[ -n "$status" ]]; then
                echo "$f"
                echo "------------------------------"
                echo "$status"
                echo
            fi
        fi
        popd >/dev/null
    fi
done
